language: python

python:
  - "2.7"

# whitelist branches
branches:
  only:
    - staging/juno-mercury

# command to install dependencies, e.g. pip install -r
# Install tox for testing neutron builds.
install: pip install tox

# command to run tests, e.g. python setup.py test
# Running neutron unit tests for python
script: 
    - tox -v -e pep8
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ./run_tests.sh -V --parallel --concurrency=4; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then ./run_tests.sh -V --parallel --concurrency=4; fi
